name: talkr_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  auto_size_text: ^3.0.0
  bottom_navigation_bar: ^1.0.1
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  date_range_picker: ^1.0.7
  device_info: ^2.0.3
  dio: ^4.0.4
  firebase_analytics_web: ^0.4.0+6
  firebase_messaging: ^11.2.5
  firebase_messaging_web: ^2.2.6
  firebase_storage: ^10.2.7
  flutter_auth_buttons: ^0.10.0
  flutter_launcher_icons: ^0.9.2
  flutter_search_bar: ^2.1.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.0
  geocoding: ^2.0.2
  geolocator: ^8.2.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  grafpix: ^1.2.8
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  lottie: ^1.2.1
  provider: ^6.0.2
  simple_animations: ^4.0.1
  url_launcher: ^6.0.18
  uuid: ^3.0.5
  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.0.13
  shared_preferences_web: ^2.0.3
  
dev_dependencies:
  cloud_firestore: ^3.1.6
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.4
  #firebase auth and core
  firebase_core: ^1.11.0

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo3.png
    - assets/images/background.png
    - assets/images/light-1.png
    - assets/images/light-2.png
    - assets/images/clock.jpeg
